import React from "react";
import { Audio } from "@remotion/media";
import { AbsoluteFill, interpolate, Sequence, staticFile, useCurrentFrame } from "remotion";
import narration from "../../narration/texte.json";
import { C } from "../theme";
import { Ending, Iris } from "./Fin";
import { Monde } from "./Story";
import { FPS } from "./util";

// 56 s at 30 fps = 28 bars of 2 s at 120 BPM (public/musique-v2.mp3, composed by outils/musique.mjs --v2).
export const DUREE_V2 = 1680;

// Voice-over (narration/texte.json, generated by narration/generer.py with Chatterbox): "femme", "homme"
// or "" for the music-only version. The music is ducked while a sentence is spoken.
export type PropsV2 = { voix: "" | "femme" | "homme" };
const PHRASES = narration.phrases;
const MUSIQUE = 0.7;
const SOUS_VOIX = 0.22;
const volumeMusique = (frame: number) => {
  const t = frame / FPS;
  const g = Math.max(0, ...PHRASES.map((p) => Math.min(
    interpolate(t, [p.debut - 0.35, p.debut], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
    interpolate(t, [p.fin, p.fin + 0.5], [1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }))));
  return MUSIQUE - (MUSIQUE - SOUS_VOIX) * g;
};

export const RelaisV2: React.FC<PropsV2> = ({ voix }) => {
  const f = useCurrentFrame();
  return (
    <AbsoluteFill style={{ backgroundColor: C.fond }}>
      <Audio src={staticFile("musique-v2.mp3")} volume={voix ? volumeMusique : MUSIQUE} />
      {voix && PHRASES.map((p) => (
        <Sequence key={p.id} from={Math.round(p.debut * FPS)} layout="none">
          <Audio src={staticFile(`voix/${voix}/${p.id}.wav`)} volume={1} />
        </Sequence>
      ))}
      {f < 46.8 * FPS && <Monde />}
      <Iris />
      <Ending />
      <Filigrane />
    </AbsoluteFill>
  );
};

// Authorship watermark: the repository address tiled diagonally over the whole picture, barely visible
// on the dark set (a single corner link is easy to crop out, a tiled one is not).
const LIEN = "github.com/nathangerardeaux/claude-relais";
export const Filigrane: React.FC = () => (
  <AbsoluteFill style={{ pointerEvents: "none", overflow: "hidden" }}>
    <div style={{ position: "absolute", left: -600, top: -500, width: 3200, height: 2200, transform: "rotate(-18deg)", display: "flex", flexDirection: "column", gap: 150 }}>
      {Array.from({ length: 12 }, (_, l) => (
        <div key={l} style={{ display: "flex", gap: 260, marginLeft: (l % 2) * 380, whiteSpace: "nowrap" }}>
          {Array.from({ length: 5 }, (_, c) => (
            <span key={c} style={{ fontFamily: "monospace", fontSize: 26, letterSpacing: 2, color: "#ffffff", opacity: 0.035 }}>{LIEN}</span>
          ))}
        </div>
      ))}
    </div>
  </AbsoluteFill>
);
